<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Application\Sonata\UserBundle\Entity\User;

/**
 * ClientSortantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientSortantRepository extends \Doctrine\ORM\EntityRepository
{
	public function getClientsSortantsOfTheStore(array $options)
	{
		$fullname 		= $options['fullname'];
		$local 			= $options['local'];
		$filters 		= $options['filters'];
		$retailManager	= $options['rm'];
		$directeur 		= $options['dr'];
		$libelleBoutiqueRattachement			= $options['libelleBoutiqueRattachement'];
		$vendorCode		= $options['vendorCode'];

		$date = new \DateTime();

		if($fullname != null && $fullname != "")
			$name = explode( " ", $fullname);
		else
			$name = "";

		switch($local) {
			case "f":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->where('c.libelleBoutiqueRattachementTopclient = :libelleBoutiqueRattachement')
		        ->setParameter('libelleBoutiqueRattachement', $libelleBoutiqueRattachement)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			case "t":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->where('c.libelleBoutiqueRattachementTopclient = :libelleBoutiqueRattachement')
		        ->setParameter('libelleBoutiqueRattachement', $libelleBoutiqueRattachement)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			default:
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->where('c.libelleBoutiqueRattachementTopclient = :libelleBoutiqueRattachement')
		        ->setParameter('libelleBoutiqueRattachement', $libelleBoutiqueRattachement)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
		}

		if($name != "" && $name != null){

			$condition = "";

			foreach ($name as $key => $val) {
				if($key == 0)
					$condition = '(c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
				else
					$condition .= 'AND (c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
			}

			if ($condition != "")
				$qb->andWhere($condition);

			foreach ($name as $key => $val) {
				$qb->setParameter(':val'.$key, "%".$val."%");
			}
		}

		$condition = "";

		if (is_array($filters)) {
			foreach ($filters as $key => $option) {
				if ($key > 0)
					$and = 'AND ';
				else
					$and = "";

				switch($option) {
					case 'inactif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat < :dateInactif ' ;
						;
					break;
					case 'actif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat > :dateInactif ' ;
						;
					break;
					case 'optin' :
						$oui = "oui";
						$in = "In";
						$_in = "IN";
						$condition .= $and.'(c.optin = :oui OR c.optin = :in OR c.optin = :_in)' ;
						;
					break;
					case 'top' :
						$condition .= $and.'c.ca3ans > 1635 ' ;
						;
					break;
					case 'newClient' :
						$oneTimer = "%One-timer%";
						$condition .= $and.'c.segmentActuel LIKE :oneTimer ' ;
						;
					break;
				}			
			}
			if ($condition != ""){
				$qb->andWhere($condition);
				if(isset($dateInactif)){
					$qb->setParameter('dateInactif', $dateInactif);
				}
				if(isset($oneTimer)){
					$qb->setParameter('oneTimer', $oneTimer);
				}
				if(isset($oui)){
					$qb->setParameter('oui', $oui);
					$qb->setParameter('in', $in);
					$qb->setParameter('_in', $_in);
				}
			}
		}
			
		if($vendorCode != "" && $vendorCode != null){
			$qb->andWhere('cs.codeVendeur LIKE :codeVendeur');
			$qb->setParameter(':codeVendeur', '%'.$vendorCode.'%');
		}
		 
		return $qb->getQuery();
	      //->getArrayResult();
			//->getResult();
	}

	public function getClientsSortantsOfTheDirector(array $options)
	{
		$fullname 		= $options['fullname'];
		$local 			= $options['local'];
		$filters 		= $options['filters'];
		$retailManager	= $options['rm'];
		$directeur 		= $options['dr'];
		$libelleBoutiqueRattachement			= $options['libelleBoutiqueRattachement'];
		$vendorCode		= $options['vendorCode'];

		if($fullname != null && $fullname != "")
			$name = explode( " ", $fullname);
		else
			$name = "";

		switch($local) {
			case "f":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.directeur = :directeur')
		        ->setParameter('directeur', $directeur)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			case "t":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.directeur = :directeur')
		        ->setParameter('directeur', $directeur)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			default:
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.directeur = :directeur')
		        ->setParameter('directeur', $directeur)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
		}

		if($name != "" && $name != null){

			$condition = "";

			foreach ($name as $key => $val) {
				if($key == 0)
					$condition = '(c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
				else
					$condition .= 'AND (c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
			}

			if ($condition != "")
				$qb->andWhere($condition);

			foreach ($name as $key => $val) {
				$qb->setParameter(':val'.$key, "%".$val."%");
			}
		}

		$condition = "";
		if (is_array($filters)) {
			foreach ($filters as $key => $option) {
				if ($key > 0)
					$and = 'AND ';
				else
					$and = "";

				switch($option) {
					case 'inactif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat < :dateInactif ' ;
						;
					break;
					case 'actif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat > :dateInactif ' ;
						;
					break;
					case 'optin' :
						$oui = "oui";
						$in = "In";
						$_in = "IN";
						$condition .= $and.'(c.optin = :oui OR c.optin = :in OR c.optin = :_in)' ;
						;
					break;
					case 'top' :
						$condition .= $and.'c.ca3ans > 1635 ' ;
						;
					break;
					case 'newClient' :
						$oneTimer = "%One-timer%";
						$condition .= $and.'c.segmentActuel LIKE :oneTimer ' ;
						;
					break;
				}			
			}
			if ($condition != ""){
				$qb->andWhere($condition);
				if(isset($dateInactif)){
					$qb->setParameter('dateInactif', $dateInactif);
				}
				if(isset($oneTimer)){
					$qb->setParameter('oneTimer', $oneTimer);
				}
				if(isset($oui)){
					$qb->setParameter('oui', $oui);
					$qb->setParameter('in', $in);
					$qb->setParameter('_in', $_in);
				}
			}
		}

		if($vendorCode != "" && $vendorCode != null){
			$qb->andWhere('cs.codeVendeur LIKE :codeVendeur');
			$qb->setParameter(':codeVendeur', '%'.$vendorCode.'%');
		}
	 
		return $qb->getQuery();
	        //->getArrayResult();
			//->getResult();
	}

	public function getClientsSortantsOfTheRm(array $options)
	{
		$fullname 		= $options['fullname'];
		$local 			= $options['local'];
		$filters 		= $options['filters'];
		$retailManager	= $options['rm'];
		$directeur 		= $options['dr'];
		$libelleBoutiqueRattachement			= $options['libelleBoutiqueRattachement'];
		$vendorCode		= $options['vendorCode'];

		if($fullname != null && $fullname != "")
			$name = explode( " ", $fullname);
		else
			$name = "";
		
		switch($local) {
			case "f":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.retailManager = :retailManager')
		        ->setParameter('retailManager', $retailManager)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			case "t":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.retailManager = :retailManager')
		        ->setParameter('retailManager', $retailManager)
		        ->andWhere('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			default:
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('u.retailManager = :retailManager')
		        ->setParameter('retailManager', $retailManager)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
		}
		
		if($name != "" && $name != null){

			$condition = "";

			foreach ($name as $key => $val) {
				if($key == 0)
					$condition = '(c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
				else
					$condition .= 'AND (c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
			}

			if ($condition != "")
				$qb->andWhere($condition);

			foreach ($name as $key => $val) {
				$qb->setParameter(':val'.$key, "%".$val."%");
			}
		}

		$condition = "";

		if (is_array($filters)) {
			foreach ($filters as $key => $option) {
				if ($key > 0)
					$and = 'AND ';
				else
					$and = "";

				switch($option) {
					case 'inactif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat < :dateInactif ' ;
						;
					break;
					case 'actif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat > :dateInactif ' ;
						;
					break;
					case 'optin' :
						$oui = "oui";
						$in = "In";
						$_in = "IN";
						$condition .= $and.'(c.optin = :oui OR c.optin = :in OR c.optin = :_in)' ;
						;
					break;
					case 'top' :
						$condition .= $and.'c.ca3ans > 1635 ' ;
						;
					break;
					case 'newClient' :
						$oneTimer = "%One-timer%";
						$condition .= $and.'c.segmentActuel LIKE :oneTimer ' ;
						;
					break;
				}			
			}
			if ($condition != ""){
				$qb->andWhere($condition);
				if(isset($dateInactif)){
					$qb->setParameter('dateInactif', $dateInactif);
				}
				if(isset($oneTimer)){
					$qb->setParameter('oneTimer', $oneTimer);
				}
				if(isset($oui)){
					$qb->setParameter('oui', $oui);
					$qb->setParameter('in', $in);
					$qb->setParameter('_in', $_in);
				}
			}
		}

		if($vendorCode != "" && $vendorCode != null){
			$qb->andWhere('cs.codeVendeur LIKE :codeVendeur');
			$qb->setParameter(':codeVendeur', '%'.$vendorCode.'%');
		}

		return $qb->getQuery();
	        //->getArrayResult();
			//->getResult();
	}

	public function getAllClientsSortants(array $options )
	{
		$fullname 	= $options['fullname'];
		$local 		= $options['local'];
		$filters 	= $options['filters'];
		$retailManager	= $options['rm'];
		$directeur 	= $options['dr'];
		$libelleBoutiqueRattachement	= $options['libelleBoutiqueRattachement'];
		$vendorCode		= $options['vendorCode'];

		if($fullname != null && $fullname != "")
			$name = explode( " ", $fullname);
		else
			$name = "";
		
		switch($local) {
			case "f":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			case "t":
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->where('c.local = :local')
		        ->setParameter(':local', $local)
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
			default:
			$qb = $this->createQueryBuilder('cs')
		 		->leftJoin('cs.client', 'c')
		        ->leftJoin('c.userTopclient', 'u')
		        ->orderBy('cs.dateArchive', 'DESC')
		        ->addOrderBy('c.ca3ans', 'DESC')
		        //->setMaxResults(1000)
		        ;
			break;
		}
		
		if($name != "" && $name != null){

			$condition = "";

			foreach ($name as $key => $val) {
				if($key == 0)
					$condition = '(c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
				else
					$condition .= 'AND (c.prenom LIKE :val'.$key.' OR c.nom LIKE :val'.$key.' ) ';
			}

			if ($condition != "")
				$qb->andWhere($condition);

			foreach ($name as $key => $val) {
				$qb->setParameter(':val'.$key, "%".$val."%");
			}
		}

		$condition = "";

		if (is_array($filters)) {
			foreach ($filters as $key => $option) {
				if ($key > 0)
					$and = 'AND ';
				else
					$and = "";

				switch($option) {
					case 'inactif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat < :dateInactif ' ;
						;
					break;
					case 'actif' :
						$dateInactif = date("Y-m-d", strtotime("-6 months"));
						$condition .= $and.'c.datedernachat > :dateInactif ' ;
						;
					break;
					case 'optin' :
						$oui = "oui";
						$in = "In";
						$_in = "IN";
						$condition .= $and.'(c.optin = :oui OR c.optin = :in OR c.optin = :_in)' ;
						;
					break;
					case 'top' :
						$condition .= $and.'c.ca3ans > 1635 ' ;
						;
					break;
					case 'newClient' :
						$oneTimer = "%One-timer%";
						$condition .= $and.'c.segmentActuel LIKE :oneTimer ' ;
						;
					break;
				}			
			}
			if ($condition != ""){
				$qb->andWhere($condition);
				if(isset($dateInactif)){
					$qb->setParameter('dateInactif', $dateInactif);
				}
				if(isset($oneTimer)){
					$qb->setParameter('oneTimer', $oneTimer);
				}
				if(isset($oui)){
					$qb->setParameter('oui', $oui);
					$qb->setParameter('in', $in);
					$qb->setParameter('_in', $_in);
				}
			}
		}

		if($vendorCode != "" && $vendorCode != null){
			$qb->andWhere('cs.codeVendeur LIKE :codeVendeur');
			$qb->setParameter(':codeVendeur', '%'.$vendorCode.'%');
		}
		
		return $qb->getQuery();
	        //->getArrayResult();
			//->getResult();
	}
}