<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientCommentRepository extends \Doctrine\ORM\EntityRepository
{

}
