<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LigneVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneVenteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNbLignes()
	{
		return $this->createQueryBuilder('l')
		 ->select('COUNT(l)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}

	public function getLignesCron($offset)
	{
		$qb = $this->createQueryBuilder('l')
			->setMaxResults(1)
        	->setFirstResult($offset)
		;

		return $qb
			->getQuery()
			->getResult();
	}
}