<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	private $year1;
	//Get count number of opt out for one campaign
	public function getTicketsOfYear(Client $client, $year)
	{
		$year1 = $year+1;

		$qb = $this->createQueryBuilder('t')
			->where('t.dateFacture < :year1')
		  	->setParameter('year1', $year1."-01-01")
			->andWhere('t.dateFacture >= :year')
		  	->setParameter('year', $year."-01-01")
		  	->andWhere('t.client = :client')
		  	->setParameter('client', $client)
		  	->orderBy('t.dateFacture', 'DESC')
		;

		return $qb
			->getQuery()
			->getResult();
	}

	public function getNbTickets()
	{
		return $this->createQueryBuilder('t')
		 ->select('COUNT(t.id)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}
}
